# Render deployment configuration
# This file is used by Render.com for deployment

# Build command: pip install --no-cache-dir -r requirements-ultra.txt
# Start command: uvicorn main_minimal:app --host 0.0.0.0 --port $PORT

# Environment variables to set in Render dashboard:
# - GEMINI_API_KEY: Your Google Gemini API key
# - BEARER_TOKEN: Secure token for API authentication
# - ENVIRONMENT: production

version: 2

services:
  - type: web
    name: document-qa-system
    env: python
    plan: starter
    runtime: python-3.11.9
    buildCommand: pip install --no-cache-dir -r requirements-ultra.txt
    startCommand: uvicorn main_minimal:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: GEMINI_API_KEY
        value: "" # Must be set in Render dashboard
      - key: BEARER_TOKEN
        value: secure-token-12345
      - key: MAX_CHUNK_SIZE
        value: 2000
      - key: TOP_K_RESULTS
        value: 5
