#!/bin/bash
# Quick Environment Setup Commands for Render

echo "=== RENDER ENVIRONMENT SETUP ==="
echo ""
echo "After your Render service builds successfully, you need to set these environment variables:"
echo ""
echo "1. Go to Render Dashboard: https://dashboard.render.com/"
echo "2. Select your 'document-qa-system' service"
echo "3. Click 'Environment' tab"
echo "4. Add these variables:"
echo ""
echo "   Variable Name: GEMINI_API_KEY"
echo "   Value: [YOUR_ACTUAL_GEMINI_API_KEY_HERE]"
echo ""
echo "   Variable Name: BEARER_TOKEN" 
echo "   Value: secure-token-12345"
echo ""
echo "5. Click 'Save Changes'"
echo "6. Your service will automatically redeploy"
echo ""
echo "=== TESTING ==="
echo "After setup, test these URLs:"
echo "- Health: https://your-app.onrender.com/health"
echo "- Web UI: https://your-app.onrender.com/"
echo ""
echo "=== API TESTING ==="
echo "curl -H \"Authorization: Bearer secure-token-12345\" \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"documents\":[{\"type\":\"text\",\"content\":\"Test document\",\"filename\":\"test.txt\"}],\"questions\":[\"What is this about?\"]}' \\"
echo "     https://your-app.onrender.com/hackrx/run"
